/*----------------------------------------------------
MASV: N17DCAT023
HO TEN: CHẾ CÔNG HẬU
LAB: 03
NGAY: 20/09/2020
----------------------------------------------------*/
CREATE TABLE SINHVIEN(
	MASV NVARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	NGAYSINH DATETIME NULL,
	DIACHI NVARCHAR(200) NULL,
	MALOP VARCHAR(20) NULL,
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY (255) NOT NULL
);
CREATE TABLE NHANVIEN(
	MANV VARCHAR(20) PRIMARY KEY,
	HOTEN NVARCHAR(100) NOT NULL,
	EMAIL VARCHAR(20) NULL,
	LUONG VARBINARY (255) NULL,
	TENDN NVARCHAR(100) NOT NULL,
	MATKHAU VARBINARY (255) NOT NULL
);
CREATE TABLE LOP(
	MALOP VARCHAR(20) PRIMARY KEY,
	TENLOP NVARCHAR(100) NOT NULL,
	MANV VARCHAR(20) NULL
);