USE QLSV
GO
CREATE PROC SP_INS_NHANVIEN (
	@MANV VARCHAR(20) ,
	@HOTEN NVARCHAR(100) ,
	@EMAIL VARCHAR(20) ,
	@LUONG INT,
	@TENDN NVARCHAR(100), 
	@MATKHAU VARCHAR(32)  )
AS
BEGIN
	DECLARE @SALARY VARBINARY (255), @MK VARBINARY (255)
	SET @SALARY = EncryptByPassPhrase ('N17DCAT023',CONVERT(VARCHAR(255),@LUONG))
	SET @MK = HASHBYTES('SHA1',@MATKHAU)
	INSERT INTO NHANVIEN(MANV,HOTEN,EMAIL,LUONG,TENDN,MATKHAU) VALUES(@MANV,@HOTEN,@EMAIL,@SALARY,@TENDN,@MK)
END