USE QLSV
GO
CREATE PROC SP_INS_SINHVIEN (
	@MASV NVARCHAR(20) ,
	@HOTEN NVARCHAR(100) ,
	@NGAYSINH DATETIME ,
	@DIACHI NVARCHAR(200),
	@MALOP VARCHAR (20) , 
	@TENDN NVARCHAR(100), 
	@MATKHAU VARCHAR(32)  )
AS
BEGIN
	DECLARE @MK VARBINARY (255)
	SET @MK = HASHBYTES('MD5', @MATKHAU )
	INSERT INTO SINHVIEN(MASV,HOTEN,NGAYSINH,DIACHI,MALOP,TENDN,MATKHAU) VALUES(@MASV,@HOTEN,@NGAYSINH,@DIACHI, @MALOP,@TENDN,@MK)
END